# Generated by Django 4.2.10 on 2026-05-04 06:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RecruiterProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(blank=True, max_length=200)),
                ("company_website", models.URLField(blank=True)),
                (
                    "industry",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("it", "Information Technology"),
                            ("finance", "Finance & Banking"),
                            ("core", "Core Engineering"),
                            ("consulting", "Consulting"),
                            ("ecommerce", "E-Commerce"),
                            ("healthcare", "Healthcare"),
                            ("education", "Education"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "company_size",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("startup", "Startup (1–50)"),
                            ("small", "Small (51–200)"),
                            ("medium", "Medium (201–1000)"),
                            ("large", "Large (1001–5000)"),
                            ("mnc", "MNC (5000+)"),
                        ],
                        max_length=20,
                    ),
                ),
                ("designation", models.CharField(blank=True, max_length=100)),
                ("phone", models.CharField(blank=True, max_length=15)),
                ("company_description", models.TextField(blank=True)),
                (
                    "company_logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="company_logos/"
                    ),
                ),
                ("city", models.CharField(blank=True, max_length=100)),
                ("state", models.CharField(blank=True, max_length=100)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recruiter_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
